[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "task-calendar"
version = "0.1.0"
description = "Desktop task calendar"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Беляев Д.В" }
]
dependencies = [
    "psycopg[binary]>=3.2",
    "PySide6>=6.7",
]

[project.optional-dependencies]
docs = [
    "Sphinx>=8.0",
]
exe = [
    "pyinstaller>=6.0",
]

[project.scripts]
task-calendar = "task_calendar.gui:main"
task-calendar-cli = "task_calendar.cli:main"

[tool.setuptools]
packages = ["task_calendar"]
